# Generated by Django 5.2.15 on 2026-06-17 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexriddleapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('secret_regex', models.TextField()),
                ('positive_example', models.TextField()),
                ('negative_example', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('kind', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_strings', to='regexriddleapi.challenge')),
            ],
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['author', '-created_at'], name='regexriddle_author__1437cc_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['is_published', '-created_at'], name='regexriddle_is_publ_ce6e85_idx'),
        ),
        migrations.AddIndex(
            model_name='controlstring',
            index=models.Index(fields=['challenge', 'kind'], name='regexriddle_challen_7832e7_idx'),
        ),
    ]
