# Generated by Django 5.2.15 on 2026-06-17 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexriddleapi', '0002_challenge_controlstring_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_regex', models.TextField()),
                ('positive_matched', models.PositiveSmallIntegerField()),
                ('negative_matched', models.PositiveSmallIntegerField()),
                ('total_positive', models.PositiveSmallIntegerField()),
                ('total_negative', models.PositiveSmallIntegerField()),
                ('solved', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='regexriddleapi.challenge')),
                ('solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['challenge', 'solver', '-created_at'], name='regexriddle_challen_bbdc45_idx'), models.Index(fields=['solver', 'solved'], name='regexriddle_solver__6522be_idx')],
            },
        ),
    ]
