# Generated by Django 5.2.15 on 2026-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexriddleapi', '0003_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='proposed_regex',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='negative_example',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='positive_example',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='secret_regex',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='controlstring',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
